name: Latest blog post workflow
on:
  push
  schedule: # Run workflow automatically
    - cron: '0 0 * * 0' # Runs once a week
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in dev.to posts
        uses: cosimameyer/.github/workflows/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@cosimameyer,https://cosimameyer.rbind.io/category/python-post/index.xml,https://cosimameyer.rbind.io/category/r-post/index.xml"
