name: Update readme with blog posts
on: 
  push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed-url: https://medium.com/feed/@cosimameyer
          commit_message: "Update blog posts"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
