name: Latest blog post workflow
on:
  push

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull in posts
        uses: cosimameyer/blog-post-workflow@master
        with:
          feed_list: "https://medium.com/feed/@cosimameyer,https://cosimameyer.rbind.io/category/python-post/index.xml,https://cosimameyer.rbind.io/category/r-post/index.xml"
